### PR TITLE
Adds tests based on documented examples

### PR DESCRIPTION
**Pull request by tomdottom**

### CODE REVIEW

**Comment by fboender** [comment]
Hi Tom!

Thanks for the work, but I'm afraid the program is already testable using the `unittest` module (error introduced deliberately):

    $ python3 jsonxs/jsonxs.py 
    **********************************************************************
    File "jsonxs/jsonxs.py", line 24, in __main__
    Failed example:
        jsonxs(d, 'feed.tags[-1]')
    Expected:
        'pytho'
    Got:
        'python'
    **********************************************************************
    1 items had failures:
       1 of  26 in __main__
    ***Test Failed*** 1 failures.

I feel that unittest is the best approach here, given the simplicity of jsonxs. It allows me to add both documentation and unittests without code duplication.

So unfortunately I'm going to close this pull request without merging it. If you disagree, please leave a comment!

**Comment by tomdottom** [comment]
Hi Ferry,

Thanks for the good work so far. I've got multiple opinions as to why I set up tests the way I did, some based on personal preference, others born of pain points I've encountered in the past.

I've tried, as best I can, to keep them separate and describe them below.


## Document how to test the package

It's very easy to assume that everyone tests the same way and knows how to test your package.
Make it easy and obvious by putting it in the documentation somewhere. Maybe a section in the README like:

```
Run Tests
---------
Given the simplicity of jsonxs doctests allow me to add both documentation and unittests without code duplication.
The tests can be run in versbose mode with:

::

    python jsonxs/jsonxs.py -v

```

## Supporting multiple python versions (use tox)

Tox is by far the best test runner I've found for running tests with different versions of python.

In fact I think this is such a great tool that I've created a separate pull request [ #4 ] for just this.

As it stands jsonxs happily works across all the most commonly used versions.

```
$ tox
...
py36 runtests: commands[0] | python jsonxs/jsonxs.py
_______________________________________ summary _______________________________________
  py27: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
SKIPPED:  py35: InterpreterNotFound: python3.5
  py36: commands succeeded
  congratulations :)
```


## Avoid dependencies between tests

Currently many of your tests have a hard coupling to a previous test. Updating any test can have a knock on effect further down the line.
This coupling also makes them hard to test in isolation, and for anyone going through the documentation by hand it requires tactic knowledge that you have to go through every step in order to get exactly the same output.

This is one of those opinions that comes from personal pain of accidentally coupling tests together and trying to track down the source of flaky tests.

Making a copy/resetting "d" before each step could easily eliminate this (but might not be so good for the clarity of the documentation),

```
# Replace a value in a list
d_copy = copy.deepcopy(d)
>>> jsonxs(d_copy, 'feed.tags[-1]', ACTION_SET, 'javascript')
>>> d_copy['feed']['tags']
['devel', 'example', 'javascript']
```

## Strong description of API behavior

In the above pull request I was trying to strongly define the behavior of each API call.
I could have made this mode explicit by using the word _SHOULD/MUST_ in the tests.

Explicitly describing the current behavior of each API was a precursor to an API change which was to come in a following pull request. Namely what happens when you set a non-existing path.

Strong organisation and description of behavior allows contributors to create new tests with recommended updates/changes.

Admittedly you could do this all with doctests, but I think you may end up with a set of doctest files that you wouldn't necessarily want to add to the documentation.

Again my personal preference is to use the unittest package to group the jsonxs api into its components and enable testing them independently if needed.

For example my workflow would typically consist of:

**Continuous testing whilst working on just the GetAction API**
```
pip install sniffer
sniffer -x tests/test_jsonsx.py:TestJsonxsGetAction
```

**Continuous testing whilst working on the entire API**
```
pip install sniffer
sniffer -x tests/
```

**Single test run on just the GetAction API**
```
pip install nose
nosetests tests/test_jsonsx.py:TestJsonxsGetAction
```

**Single test tun whilst working on the entire API**
```
pip install nose
nosetests tests/
```

# Thanks once more

Again cheers for the work on the interesting package. I hope the above was clear and coherent,

Tom

**Comment by fboender** [comment]
Hi Tom!

Thank you for your feedback. I completely agree with your points. However, I think it's important to look at the context in which you're making them. If we don't count comments and documentation, jsonxs is just a single file shy of 90 lines of code. For such a small code-base, I think you're overthinking things a bit too much here. ;-)

My goals for jsonxs are to keep it as simple and maintenance-free as possible. Right now, the tests serve their purpose. They're not perfect, but nothing ever is. I want to avoid duplicate code as much as possible, and I consider tests and documentation to be code too. I also want to avoid requiring (or making it seem like) people to install Tox just to run tests that can be run with stock python.

I'll add a bit to the README to indicate how people can run the tests.

Thanks again for your feedback!

Regards,

Ferry

**Comment by tomdottom** [comment]
Fair enough,

I've added a couple of behaviours which surprised me ( #5 & #6 ). I'll probably struggle to make much headway without my usual workflow and segmented unit tests. I'm also not that well versed in tokenizing/lexing/parsing, so maybe you'll see an easy resolution much quicker than I.

Incidentally is the _xs_ supposed to represent the lightweight nature of the package?

Tom

**Comment by fboender** [comment]
Hi Tom!

The 'xs' part is basically just an abbreviation of "access". Json access. I thought it had a nice ring to it :-) I'll have a look at the bugs you reported. From a cursory glance, it seems you're right on both counts with those.

**Comment by tomdottom** [comment]
`access` :man_facepalming: so obvious now.

I tried and address this in my own way, but one thing led to another and the lexer ballooned.
The work is at https://github.com/MediaGamma/jsonxs/tree/set-creates-path should you want to have a look.

But I suspect you'll be able to address the two issues in a simpler fashion that I did, so maybe just ignore it.

T

**Pull request closed without merging**
